id: A98271549
base_file: f58D4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:55:38.310980
  last_modified_at: 2022-06-05 19:55:38.310994
