id: A98271549
base_file: f23E5.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:55:38.305113
  last_modified_at: 2022-06-05 19:55:38.305137
